name: github-api-agent
version: '0.1.1.0'
category: Web
author: maton
maintainer: automatonix@gmail.com
copyright: 2017 maton
license: BSD3
github: matonix/github-api-agent

library:
  source-dirs: src
  exposed-modules:
  - GitHub.Request.Agent
  - GitHub.Request.Agent.Internal
  dependencies:
  - base >=4.7 && <5
  - github
  - http-client
  - unordered-containers
  - time
  - bytestring
  - case-insensitive

executables:
  github-api-agent:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - base
    - github-api-agent
    - github
    - bytestring

tests:
  github-api-agent-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - base
    - github-api-agent
